language: node_js

node_js:
  - 'stable'
  - '4.6.2'

services: mongodb

env:
  global:
    - CXX: g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
- npm run jshint
- npm test

cache:
  directories:
    - node_modules
